# configs/config.yaml
# MovieInfo 项目配置文件

# 应用配置
app:
  name: "movieinfo"
  version: "1.0.0"
  environment: "development"  # development, testing, production
  debug: true
  port: 8080

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "movieinfo_user"
  password: ""  # 通过环境变量设置
  database: "movieinfo"
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""  # 通过环境变量设置
  database: 0

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file:
    path: "logs/app.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true

# JWT配置
jwt:
  secret: ""  # 通过环境变量设置
  expire_time: "24h"
  issuer: "movieinfo"